// <auto-generated />
using System;
using ErcasCollect.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ErcasCollect.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210119141252_ChangedIdToInt")]
    partial class ChangedIdToInt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ErcasCollect.Domain.Models.Bank", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.BankDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BVN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillerId")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("OfflineId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BillerId");

                    b.ToTable("Batchs");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Biller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BillerTypeId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Commission")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Createdby")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("BillerTypeId");

                    b.HasIndex("StateId");

                    b.HasIndex("StatusId");

                    b.ToTable("Billers");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.BillerTINDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillerId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("BillerId1")
                        .HasColumnType("int");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<string>("TIN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillerId1");

                    b.ToTable("BillerTinDetails");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.BillerType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("BillerTypes");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.FundSweep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BillerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BillerId1")
                        .HasColumnType("int");

                    b.Property<int>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateProcessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("LevelOneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LevelOneId1")
                        .HasColumnType("int");

                    b.Property<string>("LevelTwoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LevelTwoId1")
                        .HasColumnType("int");

                    b.Property<bool>("isConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("isProcessed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("BillerId1");

                    b.HasIndex("LevelOneId1");

                    b.HasIndex("LevelTwoId1");

                    b.ToTable("FundSweep");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.LevelOne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BillerId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Createdby")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("FundsweepPercentage")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("BillerId1");

                    b.HasIndex("StatusId");

                    b.ToTable("LevelOne");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.LevelThree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillerId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("BillerId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Createdby")
                        .HasColumnType("int");

                    b.Property<bool>("IsAmountFixed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LevelOneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("LevelTwoId")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("BillerId1");

                    b.HasIndex("LevelOneId");

                    b.HasIndex("LevelTwoId");

                    b.ToTable("LevelThree");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.LevelTwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BillerId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Createdby")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("LevelOneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LevelOneId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("BillerId1");

                    b.HasIndex("LevelOneId1");

                    b.HasIndex("StatusId");

                    b.ToTable("LevelTwo");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.MetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillerTypeId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FieldEight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldFive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldFour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSeven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldSix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldThree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldTwo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillerTypeId");

                    b.ToTable("MetaData");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.NumberSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acronym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastDateIssued")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastIssued")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NumberSeries");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.OS", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Os");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.PaymentChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("PaymentChannels");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Pos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activationpin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Createdby")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LevelOneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LevelTwoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OSId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Version")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillerId");

                    b.HasIndex("LevelOneId");

                    b.HasIndex("LevelTwoId");

                    b.HasIndex("OSId");

                    b.HasIndex("UserId");

                    b.ToTable("Poses");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BankId1")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("BillerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaidBy")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PayerPhone")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("PaymentChannelId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceID")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("TransactionNumber")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId1");

                    b.HasIndex("BillerId");

                    b.HasIndex("PaymentChannelId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("State");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Status", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.TaxPayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Createdby")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("BillerId");

                    b.ToTable("TaxPayers");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("BillerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Createdby")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LevelOneId")
                        .HasColumnType("int");

                    b.Property<int>("LevelThreeId")
                        .HasColumnType("int");

                    b.Property<int>("LevelTwoId")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfflineBatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfflineSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentChannelId")
                        .HasColumnType("int");

                    b.Property<int>("PosId")
                        .HasColumnType("int");

                    b.Property<string>("RemittanceNumber")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("TransactionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BillerId");

                    b.HasIndex("LevelOneId");

                    b.HasIndex("LevelThreeId");

                    b.HasIndex("LevelTwoId");

                    b.HasIndex("PaymentChannelId");

                    b.HasIndex("PosId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.TransactionSummaryView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountCollected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BillerId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LevelOneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LevelOneId1")
                        .HasColumnType("int");

                    b.Property<string>("LevelTwoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LevelTwoId1")
                        .HasColumnType("int");

                    b.Property<bool>("isClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BillerId1");

                    b.HasIndex("LevelOneId1");

                    b.HasIndex("LevelTwoId1");

                    b.ToTable("TransactionSummaryViews");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillerId")
                        .HasColumnType("int");

                    b.Property<decimal>("CashAtHand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CollectionLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Createdby")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LevelOneId")
                        .HasColumnType("int");

                    b.Property<int>("LevelTwoId")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SsoId")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillerId");

                    b.HasIndex("LevelOneId");

                    b.HasIndex("LevelTwoId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.BankDetail", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Batch", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Biller", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.BillerType", "BillerType")
                        .WithMany()
                        .HasForeignKey("BillerTypeId");

                    b.HasOne("ErcasCollect.Domain.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.BillerTINDetail", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId1");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.FundSweep", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId");

                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId1");

                    b.HasOne("ErcasCollect.Domain.Models.LevelOne", "LevelOne")
                        .WithMany()
                        .HasForeignKey("LevelOneId1");

                    b.HasOne("ErcasCollect.Domain.Models.LevelTwo", "LevelTwo")
                        .WithMany()
                        .HasForeignKey("LevelTwoId1");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.LevelOne", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId1");

                    b.HasOne("ErcasCollect.Domain.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.LevelThree", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId1");

                    b.HasOne("ErcasCollect.Domain.Models.LevelOne", "LevelOne")
                        .WithMany()
                        .HasForeignKey("LevelOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.LevelTwo", "LevelTwo")
                        .WithMany()
                        .HasForeignKey("LevelTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.LevelTwo", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId1");

                    b.HasOne("ErcasCollect.Domain.Models.LevelOne", "LevelOne")
                        .WithMany()
                        .HasForeignKey("LevelOneId1");

                    b.HasOne("ErcasCollect.Domain.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.MetaData", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.BillerType", "BillerTypes")
                        .WithMany()
                        .HasForeignKey("BillerTypeId");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Pos", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.LevelOne", "LevelOne")
                        .WithMany()
                        .HasForeignKey("LevelOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.LevelTwo", "LevelTwo")
                        .WithMany()
                        .HasForeignKey("LevelTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.OS", "OS")
                        .WithMany()
                        .HasForeignKey("OSId");

                    b.HasOne("ErcasCollect.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Settlement", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId1");

                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.PaymentChannel", "PaymentChannel")
                        .WithMany()
                        .HasForeignKey("PaymentChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.TaxPayer", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.Transaction", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.LevelOne", "LevelOne")
                        .WithMany()
                        .HasForeignKey("LevelOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.LevelThree", "LevelThree")
                        .WithMany()
                        .HasForeignKey("LevelThreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.LevelTwo", "LevelTwo")
                        .WithMany()
                        .HasForeignKey("LevelTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.PaymentChannel", "PaymentChannel")
                        .WithMany()
                        .HasForeignKey("PaymentChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.TransactionSummaryView", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId1");

                    b.HasOne("ErcasCollect.Domain.Models.LevelOne", "LevelOne")
                        .WithMany()
                        .HasForeignKey("LevelOneId1");

                    b.HasOne("ErcasCollect.Domain.Models.LevelTwo", "LevelTwo")
                        .WithMany()
                        .HasForeignKey("LevelTwoId1");
                });

            modelBuilder.Entity("ErcasCollect.Domain.Models.User", b =>
                {
                    b.HasOne("ErcasCollect.Domain.Models.Biller", "Biller")
                        .WithMany()
                        .HasForeignKey("BillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.LevelOne", "LevelOne")
                        .WithMany()
                        .HasForeignKey("LevelOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.LevelTwo", "LevelTwo")
                        .WithMany()
                        .HasForeignKey("LevelTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErcasCollect.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
